RDKBDEV-2830: fix memory leak in rbus_invokeRemoteMethod
rdkcentral/rbus pull request #216
Opened 2024-08-06 23:53 UTC by pradeeptakdas

Reason for change:
1,024 bytes in 1 blocks are definitely lost in loss record 318 of 350 malloc (vg_replace_malloc.c:309)
rbus_getOpenTelemetryContextFromThreadLocal (rbuscore.c:2276) rbus_getOpenTelemetryContextFromThreadLocal (rbuscore.c:2269) rbus_getOpenTelemetryContext (rbuscore.c:2290)
rbus_invokeRemoteMethod (rbuscore.c:1064)

Test Procedure: Sanity.
Risks: None.

2024-08-06 23:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rdkcentral/rbus?pullRequest=216) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/rdkcentral/rbus?pullRequest=216) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rdkcentral/rbus?pullRequest=216) it.</sub>

2024-08-07 13:10 UTC, pradeeptakdas commented
Internal ticket created for tracking https://ccp.sys.comcast.net/browse/RDKCOM-4964

2024-08-27 15:58 UTC, karuna2git requested changes
Release of TelemetryContext must happen only at connection close

2024-09-10 16:28 UTC, pradeeptakdas commented
Hi @karuna2git 
Can you please review and merge this PR? Please let LGI team know if you have any review comments.

2024-10-02 19:26 UTC, karuna2git approved these changes

2024-10-03 13:50 UTC, merged